# Generated by Django 5.0.1 on 2025-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao_horas',
            field=models.PositiveIntegerField(default=0, help_text='Duração total do curso em horas'),
        ),
        migrations.AddField(
            model_name='curso',
            name='materiais',
            field=models.TextField(blank=True, help_text='Materiais complementares do curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivos',
            field=models.TextField(default='', help_text='Objetivos de aprendizagem do curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='pre_requisitos',
            field=models.TextField(blank=True, help_text='Pré-requisitos necessários para o curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='publico_alvo',
            field=models.TextField(default='Não especificado', help_text='Público-alvo do curso'),
            preserve_default=False,
        ),
    ]
